In [ ]:
#Q1 Write a Python program to create an array of 5 integers and display the array
# Access individual element through indexes
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(arr[0])
print(arr[2])

[1 2 3 4 5]
1
3


In [ ]:
#Q2 Write a Python program to reverse the order of the items in the array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr[::-1])

[5 4 3 2 1]


In [ ]:
#Q3 Create a 4X2 integer array and Prints its attributes
#The shape of an array.
#Array dimensions.
#The Length of each element of the array in bytes.
import numpy as np
arr = np.array([[1,2],[3,4],[5,6],[7,8]])
print("Shape: ",arr.shape)
print("Dimension: ",arr.ndim)
print("Length: ",arr.nbytes,"bytes")

Shape:  (4, 2)
Dimension:  2
Length:  64 bytes


In [56]:
#Q4 return array of items in the third column from all rows in the following nump
# ([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
import numpy as np
arr = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
print(arr[:,2])

[33 66 99]


In [ ]:
#Q5 Create a result array by adding the following two NumPy arrays
# arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
# arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
import numpy as numpy
arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
result = arrayOne+arrayTwo
print("Result array: \n",result)

Result array: 
 [[20 39 33]
 [25 25 28]]


In [50]:
#Q6 Sort the previous array
import numpy as np
result = np.array([[20,39,33],[25,25,28]])
resort = np.sort(result)
print(result)
print(resort)

[[20 39 33]
 [25 25 28]]
[[20 33 39]
 [25 25 28]]
